### ISSUE TITLE
Unable to encrypt page with only H1 and text

### ISSUE THREAD

**Issue by martinbira** [CoinK0in/mkdocs-encryptcontent-plugin#11]
I tried to encrypt a page today containing only an H1, `# Title`, and some text and it did not work until I added an additional H2 section, `## Subtitle`. The following error message was received:

```
File "c:\users\mbj\appdata\local\programs\python\python38\lib\site-packages\encryptcontent\plugin.py", line 255, in on_post_page
    merge_item = item.contents[0]
IndexError: list index out of range
```

**Expected behaviour:**
Page is encrypted when only containing an H1 tag and some text.

**Current behaviour:**
`mkdocs build` or `mkdocs serve` breaks.

**Steps to reproduce:**
1.  Create an encrypted page with only an H1 title and body text.
2. Run `mkdocs serve` or `mkdocs build`.

**Comment by CoinK0in** [comment]
Thanks for your feedback.

Indeed in some cases the target HTML element of the "encrypt something" feature may be empty. 
This is the case with the Material theme, in the ToC menu, if the page have only one title.

[Version 0.0.12](https://github.com/CoinK0in/mkdocs-encryptcontent-plugin/releases/tag/0.0.12) fix this issue.

**Comment by martinbira** [comment]
Works with my tests. Closing the issue.
