### ISSUE TITLE
when password is number，it error

### ISSUE THREAD

**Issue by wojiazaiyugang** [CoinK0in/mkdocs-encryptcontent-plugin#17]
![image](https://user-images.githubusercontent.com/14771322/134472518-8237d53e-f3ac-43e5-b688-70414f1dfba8.png)

![image](https://user-images.githubusercontent.com/14771322/134472506-28f0a47c-2ad4-4fa5-8f88-f7485499f8cd.png)

**Comment by CoinK0in** [comment]
Hi,

[Version 1.2.2](https://github.com/CoinK0in/mkdocs-encryptcontent-plugin/releases/tag/1.2.2) should fix this problem. 

Thank you for the feedback.
