### ISSUE TITLE
Using the plugin with navigation.instant

### ISSUE THREAD

**Issue by anthares101** [CoinK0in/mkdocs-encryptcontent-plugin#18]
Hello, I noticed that when enabling the `navigation.instant` feature in mkdocs material theme the plugin is not working as expected:
 - Sometimes after using the decrypt button with the correct password the page needs to be reloaded in order to get it shown.
 - If the user has a cookie with the password for an article, the plugin is not able to decrypt it until the page is, once again, reloaded.

Maybe this can help because looks like the same problem: https://stackoverflow.com/questions/63145812/mkdocs-material-latex-not-rendering-in-instant-mode

Thanks for your work!

**Comment by CoinK0in** [comment]
Hello,

Well, I finally found the motivation to take a closer look and dig deeper into this issue :)

I learned about how js / ajax works and found a solution that solves this reload / decryption problem.

I will be pushing a version with this patch in the next few days in the [Experimental](https://github.com/CoinK0in/mkdocs-encryptcontent-plugin/tree/experimental) branch.  I still need to fix and reorder my code, it's a bit of a mess.

I would make a comeback here at that time.

**Comment by CoinK0in** [comment]
I publish a new major version ([Version 2.0.0 Experimantal 1](https://github.com/CoinK0in/mkdocs-encryptcontent-plugin/commit/9b8db06e339817f89c2957b2bf4ff63e5e02fcac)) of the plugin which fixes your browsing problem and adds the latest branch master fixes in addition to the search index management functionality.

It is not available on Pypi.org, you have to install it [manually from source](https://github.com/CoinK0in/mkdocs-encryptcontent-plugin/tree/experimental#installation) if you want to try this version.

You can then uninstall this version with :
```shell
cd ./mkdocs-encryptcontent-plugin
rm -fr build/ dist/ mkdocs_encryptcontent_plugin.egg-info/ 
pip3 uninstall mkdocs-encryptcontent-plugin -y
```
Any feedback you can make on this version is welcome. 
Thank you.

**Comment by anthares101** [comment]
Hey! I was able to test the branch and everything looks like is working. Do you know how much time you would need to move the new version to the master branch and Pypi?

Thanks for your work!

**Comment by CoinK0in** [comment]
I would have liked to have had more feedback but I think it would take a little while to get some and I'm pretty convinced by the code for this version after some testing, so I will probably do it next weekend. I will have to manage for the occasion the transition of certain master options which no longer exist so as not to break anything, but there should be no problem. 

Thanks you for your feedback :)

**Comment by anthares101** [comment]
Perfect! I will let this open until then, people normally use the Pypi version and if they have this issue they can easily see that will be fixed soon ^^

Thanks for your time!

**Comment by anthares101** [comment]
Hello man! I saw that you uploaded the new version to Pypi! Everything is working so I will close the issue.

Thanks!
