### ISSUE TITLE
Support for mermaid2

### ISSUE THREAD

**Issue by ishapiro** [CoinK0in/mkdocs-encryptcontent-plugin#22]
When this module was active, I noticed that the Mermad2 plugin no longer renders the graphs.  Instead, the raw graph is output.

https://github.com/fralau/mkdocs-mermaid2-plugin

**Comment by CoinK0in** [comment]
I added a detection of the Mermaid2 module which, if present, should relaunch the rendering process.
No additional configuration is needed for  [Mermaid2 support](https://github.com/CoinK0in/mkdocs-encryptcontent-plugin#mermaid2-support).

[Version 2.1.0](https://github.com/CoinK0in/mkdocs-encryptcontent-plugin/releases/tag/2.1.0).

**Comment by ishapiro** [comment]
Outstanding.  Thanks.

Irv
- - - - - - - - -

[image: photo]
*Irv Shapiro | Personal Email*
Cogitations, Inc.

Mobile: 847 331 1310 | ***@***.***

http://www.cogitations.com
<https://mailtrack.io/trace/link/e83568109c32c2ac12de7e612190981a17f7e72d?url=http%3A%2F%2Fwww.cogitations.com&userId=2835845&signature=ff9e32bb91bb8438>

<https://mailtrack.io/trace/link/b2b25fe75c451a0c1cbfdf0400d4fd6a61ac3c22?url=http%3A%2F%2Fus.linkedin.com%2Fin%2Firvshapiro&userId=2835845&signature=c32ff6fd27139027>
<https://mailtrack.io/trace/link/8d321eb2a983e9f078cc0b25896ceefe3af10a1b?url=http%3A%2F%2Ftwitter.com%2Firvshapiro&userId=2835845&signature=a864dcbe36e6300d>
