### ISSUE TITLE
Question: Protect one page?

### ISSUE THREAD

**Issue by e5k** [CoinK0in/mkdocs-encryptcontent-plugin#23]
Hey,

Sorry but I don't quite get how to protect one single page with a meta tag. Could you provide an example?
Thanks a lot

**Comment by CoinK0in** [comment]
Do not define the "global_password" variable in your mkdocs.yml config file, as result you don't have encrypted the articles / pages by default. And add on each header, of the articles / pages that you want to be protected, `password: <your password>`. 

More concretely, in your mkdocs.yml file :
```markdown
[ ... ]
plugins:
  - search: {}
  - encryptcontent: {}
[ ... ]
```
In your `docs/article_n1.md` :
```markdown
password: <your_password>

# Ttitle

Default text ... continue article
```

**Comment by e5k** [comment]
As simple as that :) 
Thanks a lot for the fast answer!
