### ISSUE TITLE
override decrypt-form.tpl.html

### ISSUE THREAD

**Issue by unverbuggt** [CoinK0in/mkdocs-encryptcontent-plugin#32]
Hi,

is it possible ot override decrypt-form.tpl.html somehow? I haven't found another way then changing the file in the site-packages which is overwritten after each pip upgrade.

The html template is simple, just a input and optional button element without assigned css classes or style tag.
It looks acceptable on mkdocs theme, but not so well on others.

**Comment by CoinK0in** [comment]
I added several configurations to allow the override of the templates used *(JS and HTML)*.
Details of this feature are described here [Override default templates](https://github.com/CoinK0in/mkdocs-encryptcontent-plugin#override-default-templates).

[Version 2.3.0](https://github.com/CoinK0in/mkdocs-encryptcontent-plugin/releases/tag/2.3.0).

**Comment by unverbuggt** [comment]
Wow, this resolves all of my small problems. Thank you very much.

**Comment by CoinK0in** [comment]
Thank you for the suggestions for improvements. Sry for your PR.
