### ISSUE TITLE
Use one password for a folder

### ISSUE THREAD

**Issue by zerenxyz** [CoinK0in/mkdocs-encryptcontent-plugin#37]
Is it possible to use this plugin to require password for one whole subfolder of docs and not individually for each page in that folder?
```
├─ docs/
│  ├─ folder_A/
│  │  ├─ index.md
│  │  ├─ general.md
│  │  ├─ info.md
│  │  └─ extra_info.md
│  ├─ folder_B/
│  │  └─ etc...md
└─ mkdocs.yml
```

How do I make it so folder_A has one password, and if entered it opens all the pages inside that folder so you dont have to enter a password for each page one by one.

**Comment by zerenxyz** [comment]
I am running into an issue where only my index.md and random page accepts the global_password

All other pages say invalid password where I dont have set anything in any of the pages, not sure what I am missing here, using CTRL+ENTER to enter global password also doesnt work

**Comment by CoinK0in** [comment]
The functionality of a password per subfolder will not be done.
