### ISSUE TITLE
Crypto module not found & module 'mkdocs.utils' has no attribute 'string_types'

### ISSUE THREAD

**Issue by anthonyeden** [CoinK0in/mkdocs-encryptcontent-plugin#4]
I had some issues starting this for the first time.

        from Crypto import Random
        ModuleNotFoundError: No module named 'Crypto'

To solve this on Mac OS, I had to run:

    pip3 uninstall crypto
    pip3 uninstall pycrypto
    pip3 install pycryptodome

This may not be an issue with this plugin, but I wanted to document it here in case someone else has the same issue.

**Comment by CoinK0in** [comment]
PyCrypto is no longer recommended and pycryptodome seems to replace it. 

I added pycryptodome at the same time as [this commit](https://github.com/CoinK0in/mkdocs-encryptcontent-plugin/commit/4bfc4f75234166b51104feed5fbb243f205dcfee#diff-2eeaed663bd0d25b7e608891384b7298)

Tell me if it's enough or if you see something else to do to force the use of pycryptodome.

Thanks for your feedback.
