### ISSUE TITLE
Preventing being promoted for password on each page

### ISSUE THREAD

**Issue by arnonzooz** [CoinK0in/mkdocs-encryptcontent-plugin#6]
Hi

I like the plugin! My only issue is that you need to enter the password again and again on each page you're trying to view (unless I missed something?). Is there a way around it? So if you entered a password on one page, you do not have to enter it again during your session?

Thanks

**Comment by CoinK0in** [comment]
Hey, 

You haven't missed a thing ^^ '

I tried to make a new feature to meet your request. 
Although I am absolutely not satisfied with the result, I added it to the 'master' branch here : (issue #6)[https://github.com/CoinK0in/mkdocs-encryptcontent-plugin#rebember-password]

Personally, I use KeepassXC, to do not to have to enter/remember my passwords, but let me know if its ok for you or if you have any other idea for the implementation of your request.
